### PR TITLE
Initial packaging of libcurl

### PR DESCRIPTION
**Pull request by smalldave**

### CODE REVIEW

**Comment by anttikantee** [comment]
Thanks, looks good.

Did you test that it works?

Can you improve the description to include a few words on what libcurl is, for the benefit of those who might not know.  "packaging of x for rumprun" is redundant, it's implied by the repository ;-)

I'll invite you to the rumprun-packages team in a few moments, and after accepting you can merge this PR.

**Comment by anttikantee** [comment]
Oh, does the email address you listed for maintainer work now?

**Comment by smalldave** [comment]
I've tested it works. Run it from a completely clean Docker container and builds fine.

I'll add some blurb.

I've tried that email from a couple of my other email addresses. Seems to work fine for me.
Feel free to send me an email.

**Comment by anttikantee** [comment]
I meant if you checked that the built library works, not only if it can be built.  Unsure which your answer means.

btw, add the email address you're committing with to your github account.

**Comment by smalldave** [comment]
oh you mean actually works.
looking at that now.
will let you know.

**Comment by anttikantee** [comment]
Ok, thanks.  Merge after it works, as in at least one program runs against libcurl.  Based on prior experience, I don't expect trouble, but you never know ...

**Comment by smalldave** [comment]
on an ec2 instance gets as far as "can't resolve host". Not sure if that counts as working but it is definitely doing something.
i'm done for the day so can get back to this tomorrow

**Comment by smalldave** [comment]
that is returned from libcurl BTW

**Comment by anttikantee** [comment]
DNS is not configured unless you know where to hack it in, so that would be one reason you get that error ;-)

Testing on EC2 is quite painful, I'd recommend using something like qemu locally and only when you get things fully working, test on EC2.

**Comment by anttikantee** [comment]
I added an empty resolv.conf to rumprun-packages/stubetc/etc.  That's what you need to edit.  One well-known public DNS server is at 8.8.8.8 (which you should use only if you trust Google).

**Comment by smalldave** [comment]
Ok. 
I quite like the idea of not having any file system drivers.
If I care enough it's not too difficult to roll your own dns client.
Think I can live without DNS for a bit anyway.

**Comment by smalldave** [comment]
Switched to IP addresses and it all worked fine.

**Comment by anttikantee** [comment]
Great, then please merge your pull request!

Thanks!

**Comment by smalldave** [comment]
Do I have the right to push?

**Comment by anttikantee** [comment]
On 13/01/16 12:06, David Smith wrote:

> Do I have the write to push?

Yes, after you accept the invitation the rumprun-packages team.

**Comment by smalldave** [comment]
I've not received that. Email problems again?

**Comment by anttikantee** [comment]
On 13/01/16 12:15, David Smith wrote:

> I've not received that. Email problems again?

I don't know what precisely went wrong, as I don't have access to 
github's logs.  In any case, the email is not critical, since you accept 
the invitation from the github web ui.

**Comment by smalldave** [comment]
As far as I know I haven't received any notification via the ui or through email that I was invited to join the packages team.

**Comment by anttikantee** [comment]
On 13/01/16 13:37, David Smith wrote:

> As far as I know I haven't received any notification via the ui or through email that I was invited to join the packages team.

I tried clicking "update invitation" for you.  No idea if that sends 
another email.

Also, the box says: "Invitations are sent via email and can be accepted 
at https://github.com/rumpkernel"

If you still don't get emails or can't accept, I can't do anything else, 
since I don't see into github's internals.

**Comment by smalldave** [comment]
I hadn't gone to the org home page. I've accepted now. Ta.
Not sure what is happening to the email

**Pull request merged**
