### PR TITLE
Add apache2 httpd package

### PR DESCRIPTION
**Pull request by myunghoj**
Hi!

I added apache http server 2.4.20 and tested. It works fine with general html web pages and also https with ssl. If there is anything wrong, please let me know :)

Thanks,
Myungho (mhjungk@gmail.com)

### CODE REVIEW

**Comment by anttikantee** [comment]
Thanks!  I remember making Apache work against a TCP/IP stack provided by a rump kernel I think in 2008 (which wasn't a "pure" unikernel back then), so this brings back some memories.

Some bits in `APACHE_CONF_ENV` look wrong.  For example, Rumprun does not support `TCP_CORK`.

I hope you will work with upstream to merge your patches.

I will invite you to the packages team, and after joining you can merge this PR at your discretion.  Thanks!

**Comment by anttikantee** [comment]
Oh, and also please add apache2 to `.travis.yml`

**Comment by myunghoj** [comment]
Hi Antti!

Thank you so much for invitation. I just merged and added it to travis.

**Comment by anttikantee** [comment]
Great, thanks!

**Pull request merged**
