### PR TITLE
Set up ccache manually since language doesn't match C/C++

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Yup that works...

**Comment by anttikantee** [comment]
ok, let's see how this one fares, then ;-)

**Comment by thedrow** [comment]
Yup. It works really well.
See https://travis-ci.org/rumpkernel/rumprun-packages/builds/139942332 comparing to https://travis-ci.org/rumpkernel/rumprun-packages/builds/139803358.

**Comment by anttikantee** [comment]
Cool!

**Pull request merged**
