### PR TITLE
Enable ccache for faster builds

### LINKED ISSUE #110: Use ccache in build
ccache has been available in Travis for a while now and all of these packages require a C/C++ compiler.
I think this will speed up build times by a lot.

### PR DESCRIPTION
**Pull request by thedrow**
This will fix #110

### CODE REVIEW

**Comment by anttikantee** [comment]
Cool, thanks.  Easier than I thought ;-)

Let's see how it fares.

**Comment by thedrow** [comment]
Actually it's not working since the language of the build must be C/C++. I can set it manually if you prefer?

**Comment by anttikantee** [comment]
What does the language do, exactly?  Not all of the packages are compiled purely with a C/C++ compiler, though those ones typically bootstrap the compiler themselves first.

**Comment by thedrow** [comment]
It sets up a CPP compiler.

**Comment by thedrow** [comment]
@anttikantee See #112

**Pull request merged**
