### PR TITLE
Adds Incognito as maintainer of Libxml2

### PR DESCRIPTION
**Pull request by Incognito**

### CODE REVIEW

**Comment by anttikantee** [comment]
If you want to be maintainer, you should just push ;-)

**Comment by Incognito** [comment]
Do I have write access to this repo?

**Comment by anttikantee** [comment]
This computer game is too complicated for me.  I'll just go back to playing nethack.

**Comment by Incognito** [comment]
pushed

**Comment by anttikantee** [comment]
Thnx.

For future reference, I think you are also able to merge pull requests from the web ui.

**Pull request closed without merging**
