### PR TITLE
initial ruby work

### PR DESCRIPTION
**Pull request by reuben-sutton**
Builds and runs but isn't useful yet

### CODE REVIEW

**Comment by anttikantee** [comment]
Thanks, but why not wait until it's useful?  Shouldn't take very long, or?

**Comment by anttikantee** [comment]
Btw, I'm not sure if stdout is not working or your command is wrong.  The rumprun tool is a bit suboptimal in the sense that the shell interprets the quotation first.  So try replacing `-e "puts 'hi'"` with something like `-e '\"'puts \'hi\''\"'`

**Comment by anttikantee** [comment]
Can you convert this to use RUMPRUN_GENISOIMAGE (see #35).

Adding 430+ files for an example is not acceptable, can you radically trim it down?

Is there anything else which prevents initial ruby support from being merged?

**Comment by reuben-sutton** [comment]
Hi @anttikantee 

Sorry about the delay on this, all cleaned up and working now.

**Comment by anttikantee** [comment]
Thanks.  Meanwhile, we formulated a policy that new packages must have maintainers.  I've forgotten to update the README (will do so in a few hours), but see this thread:
https://www.freelists.org/post/rumpkernel-users/proposal-maintainers-for-rumprunpackages

**Comment by reuben-sutton** [comment]
Great, I've added myself as the maintainer in the README.md

**Comment by anttikantee** [comment]
One more nit: the GENISOIMAGE calls in the Makefile should not use `-hfs -joliet`.

Since you took maintainership, you get push access, so you can merge this request yourself at your convenience (preferably after fixing the `-hfs -joliet` issue ;-).

**Pull request merged**
