### PR TITLE
Fix nodejs build

### PR DESCRIPTION
**Pull request by davedoesdev**
#26

### CODE REVIEW

**Comment by anttikantee** [comment]
Does something useful happen with just `make`?  It would be useful to reach that goal, especially for autobuilds.

**Comment by davedoesdev** [comment]
https://github.com/davedoesdev/rumprun-packages/tree/fix-nodejs-build/nodejs#instructions

**Comment by anttikantee** [comment]
Thanks.  Was looking just at the diff, and it seemed to add various git-checkout and other requirements, but it's good to know those are optional.

**Comment by davedoesdev** [comment]
Yes, they're for the examples. The git-checkout is to reset the default file in case you previously ran the bundle example.
I've been thinking in that area to make it easier (especially for native addons), hope to do something soon.

**Comment by anttikantee** [comment]
Nice, thanks.

**Pull request merged**
