### PR TITLE
Add Open vswitch unikernel

### PR DESCRIPTION
**Pull request by huikang**

### CODE REVIEW

**Comment by anttikantee** [comment]
Thanks. Do you want to be the maintainer? (see "Contributing new packages" in the rumprun-packages README)

**Comment by huikang** [comment]
Sure, I would like to be the maintainer for the ovs component. The readme is updated. Thanks.

**Comment by anttikantee** [comment]
Thanks.

1) maybe better to use rumprun kvm by default?
2) please add the package to `.travis.yml`

I'll send you an invitation for push access, you can then merge this PR yourself.

**Comment by huikang** [comment]
Glad to join the project. Since most of the applications in rumprun-package repo uses qemu as the platform argument in the rumprun command, I just want to be consistent. However, as you suggested, I added a note about ``kvm`` in the ovs/README.md. Thanks.

**Comment by anttikantee** [comment]
great!

**Pull request merged**
