### PR TITLE
Add Tor support

### PR DESCRIPTION
**Pull request by gandro**
This adds the Tor package. All the work was done by @supradix in his repo over at [supradix/rumprun-packages](https://github.com/supradix/rumprun-packages/tree/amonk-master) (issuing this PR with his permission).

### CODE REVIEW

**Comment by anttikantee** [comment]
@supradix thanks

@gandro Any reason you're not reviewing and merging the contribution yourself?

**Comment by gandro** [comment]
I wanted to see if anybody had any comments on it. I will merge if there are no complaints.

**Comment by anttikantee** [comment]
If you think it's ok to merge, I won't look at it ;-)

btw, IIRC, tor is the second user-oriented (i.e. non-kernel hacking) use case for rump kernels I proposed in ~2008 (first was fs-utils in 2007), so this application is very close to my heart.

**Comment by gandro** [comment]
@supradix Looking at the use of sudo in the Makefile, I'm wondering if the config files have to be writable? If not, you could generate an ISO with `$(RUMPRUN_GENISOIMAGE)` for the config files, and just generate an empty ext2 image for `DataDirectory`. The [redis package](https://github.com/rumpkernel/rumprun-packages/blob/9e44d1468a19d041372205e2e4941834fc4b0604/redis/Makefile#L28) does the same.

**Comment by supradix** [comment]
@anttikantee You're welcome.  Glad it's near and dear.  Seemed a perfect marriage to me too. :)

@gandro Github seems to not let me create the pull request, not matter what I try, which is what ended up causing me to create the messed up one on my own repository last week, now that I recall.  I am now wondering though, if this gets merged from the copy you kindly created a pull request for, will I not get credit for the contribution on my github page when it is merged?

**Comment by supradix** [comment]
@anttikantee Oh, and thank you for rump in the first place!  Very cool.  (Sorry, I'm just waking up again.)

**Comment by gandro** [comment]
@supradix Your name will show up in the commit history, but I don't think it will show up in your GitHub profile. I'm happy to close this PR if you want to try it yourself again for the fame :)

Here's what I think you need to do:
1. keep a local copy of your rumprun-packages git repo
2. delete your rumprun-packages repository on GitHub, and recreate it by using the "Fork" button on rumpkernel/rumprun-packages
3. in your local git repo, make the `origin` remote points to the freshly created fork (`git remote -v`)
4. push your amonk-master branch to your freshly created fork with `git push -u origin amonk-master`
5. open a pull request on this repository

And while your at it, you could also link the mail address you use in git commits in your GitHub profile, so your commit messages are actually linked to your GitHub account.

**Comment by supradix** [comment]
@gandro Yes, I would like it to show up in my github profile "for the fame," as you say, so I'll follow your direction.  Also, this morning on freenode, you posted the following comment in #rumpkernel...

"(06:50:20) gandro: it seems that supradix/rumprun-packages is not considered a fork by github.. strange"

Is that why github won't let me create a pull request for it on rumpkernel/rumprun-packages?

Also, I'm now fearing that this comment thread will end up lost even when I get a proper pull request established at this point.  Bummer.  Oh, why is everything that should be hard easy, and everything that should be easy hard?  Oy vey. :-/

As I mentioned while passing out on IRC this morning, I'm not very github savvy yet, so the mess is probably all my fault from lack of familiarity.  Sorry.  But the result looks to be headed toward some suckage.  Oh well, such is life.  Maybe this thread will still exist and I can link it in at the top or something at least.

**Comment by anttikantee** [comment]
Don't feel bad about not understanding git(hub), I don't either.  My take is that anyone who doesn't want to understand such a complicated way to store revisions still has some hope left.  (then again, I might just be making up excuses for being lazy)

**Comment by supradix** [comment]
@gandro Regarding your filesystem suggestion, I originally created the package utilising genisoimage as well, very much as you suggest, since the config files do no have to be writable, but I later decided that the additional complication of having two different filesystem images wasn't really justified, so I just merged it all into the one, writable ext2 image.  I'm not sure I understand your point about "no reason to mount it" though.  If it's not mounted, how can it be used?

Also, for a while in the middle there, I was using tuple-cookfs to create a custom [read only] stub /etc image at one point too (which seemed a cleaner option than using genisoimage, imho), but I was having trouble getting it to mount in place of the default stub /etc.  My intention was to have the tor config directory in /etc/tor, as POLA would prefer anyway, _and_ to customise the unikernel's /etc with a functional resolv.conf and custom passwd/group/*.db files containing a tor user so I could set "User tor" in torrc.  But, I got impatient/frustrated with it all (wasn't getting much response on #rumpkernel at the time) and so just ripped it down to the single, writable ext2 image for now.  I will not be satisfied until I get this route working though. :)

Additional thoughts?

**Comment by supradix** [comment]
@anttikantee Thanks.  I concur.  And even contend that without a _healthy_ lazy quotient, there is no path to Zen. ;)

**Comment by supradix** [comment]
And I hate having to use a web browser to do anything these days, including "simply" browsing what _should_ be static web text... which doesn't really motivate me in github's direction very much, of course, so I think I'm kind of handicapped even. ;)

**Comment by gandro** [comment]
@supradix Regarding the filesystem, my remark about "no reason to mount it" (which I removed after posting, since I realized it was confusing ;-) ) was referring the `sudo mount -o loop ...` in the Makefile, not the running unikernel. You are right of course, you need to mount both in the unikernel. In any case, given your statement, I'm happy to leave it as it is right now.

> Is that why github won't let me create a pull request for it on rumpkernel/rumprun-packages?

Yes, I think without clicking on the fork button (or using a CLI tool that uses the GitHub API to do this), you cannot submit pull requests. I will leave this PR open until you submit one under your own name. And don't worry about the comments in this thread, they will be archived by GitHub ;)

**Comment by supradix** [comment]
@gandro So, with your generous assistance, I think I have it submitted properly now.  Thanks much. :)

**Comment by anttikantee** [comment]
Using `sudo` or `mount` for building the package is definitely not acceptable.  If you really need a populated ext2 image, use `genext2fs`.

**Comment by gandro** [comment]
Fair enough. I think it would be easiest to split up configuration files and data directory as mentioned above, I did not know about `genext2fs` though, good tip. 

I can give it a try (not before the end of the week, though), thus @supradix feel free to work on this. :)

**Comment by anttikantee** [comment]
I didn't look into how exactly tor uses files, but generally yea, you can split them.  You can even use cookfs for the config files, if that makes more sense.  (I designed the `-m cmd` in rumprun-bake to be easy to copy-paste).

**Comment by supradix** [comment]
Yeah, I wasn't very happy with the use of sudo in the Makefile either, and in fact wouldn't have done so if the package was just for me, but I acquiesced to using it in order to make the result of building be immediately usable, automagically, without others having to first do manual preparation work.  I wasn't aware of genext2fs either though.  That looks much preferable.  Thanks.  I'll change it to use genext2fs for now, but as I mentioned a few comments above (which you seem to have missed, anttikantee?), I ultimately intend to use cookfs to store the tor config (and some other files: resolv.conf, passwd stuff, etc.) in the stub /etc that gets embedded into the rump image.  I was using tuple-cookfs and the rumprun-bake "-m cmd" option for that, and all seemed to go well, but then the modified stub /etc didn't seem to be available in tor.bin in the end (or, at least my modifications weren't found).  In any case, I'm confident whatever problem I was having there can ultimately be resolved, especially now that I have the assistance of you two).  Ultimately, I'm after just a blank, writable disk image for tor's data, and a custom cookfs /etc stub in the rump image.  This way, tor's config will be read only while not requiring an extra image file, _and_ /etc can be customized with a working resolv.conf _and_ addition of a tor user so tor can be run unprivileged as well (even though probably not all that necessary, what with it running in a unikernel and all, but I'd still prefer the additional layer of security on principle).

**Comment by anttikantee** [comment]
Note that you cannot use a cooked file system to override files in the default `/etc` without first removing the default `/etc` entirely.  The idea with that semantic is to keep "oops I didn't want that version of that file to silently override the version I actually wanted" from happening.

**Comment by anttikantee** [comment]
I made the image building a manual step and documented that step in the README (hopefully got it right on the second try).  With that done, I think there's no critical rush to fix it.

@supradix can I trouble you to post about your work to the rumpkernel list?  I'm interested especially in your motivations and experiences so far.  If the post is understandable to someone not intimately familiar with tor (e.g. me), all the better.

**Comment by supradix** [comment]
Heh.  I automated the image building with your excellent genext2fs suggestion, and documented it in the readme as well, and rather extensively, in fact, because I also decided to limit the image's inodes to exactly what is required for tor, and no more, effectively making tor run on a read only filesystem for any purposes other than its own.  I was really anal about it though, so it took me a while, and I haven't pushed it yet because I'm still testing the inode restriction addition.

Also, that travis build breakage did seem to be a problem with the package to me.  When I initially created it, I had no problem building it, but when I went to work on it again in a new shell, I got the same error.  I tracked it down and resolved it as well though.  Seems I had a more capable shell environment than I was aware of before.

How should we handle the potential conflict?

Sure, I can post about it.  I'm the really slow and methodical sort though, so it will take me a bit.  And, I seem to be pretty "weird" too, by all accounts, so that may well show through some as well, but I'll try to throttle it as much as possible. ;)

**Comment by supradix** [comment]
Also, shouldn't we move continued discussion to https://github.com/rumpkernel/rumprun-packages/pull/102 now?

**Comment by supradix** [comment]
And, finally, I do still intend to finish the cookfs approach as well, but I just wanted to tidy up what existed now first.

**Comment by anttikantee** [comment]
What potential conflict?

I don't mind slow.  I thought I was a slow and therefore poor writer, but then I watched some interview of Don Knuth where he said it might take him a week to write a sentence because he wants it to be correct; made me feel better about myself.

Discussions should move to the "one issue per thread" model, but I'm not even currently on the map about what all the issues are.

**Comment by anttikantee** [comment]
... not that my sentences end up being correct, but at least I got the slowness.

**Comment by supradix** [comment]
About "potential conflict," I just meant about how your changes and my changes might collide problematically.  It's probably a trivial, non-issue to people who have worked with revision control with others a lot, but I've mostly only used it alone, so I have very little experience in the conflict resolution department.  That's all.  Just my worries.

I straight prefer slow.  My standard mantra is, "You can have fast or you can have good.  You can even have pretty fast and pretty good.  I can do that too, if you want.  But you can't have fast and good.  They are mutually exclusive.  Shit takes time, and good shit takes more of it." :)

As it so happens, my father went to Case Tech with Knuth.  It was one of very few schools with a computer at the time.   They had a building for their computer and everything.  It was very advanced. :)

I have an undergraduate degree in writing, as it so happens as well, so I'm super crippled (lol), and I've read some of your writing, at least in English, and you write quite well, especially considering English isn't even your native language.  You know who always impressed the hell out of me in this category though?  Joseph Conrad.  He didn't speak a word of English until he was a young adult, and became arguably one of the greatest English prose stylists in history.  Yeah, we suck. lol

**Comment by supradix** [comment]
Also, I see that you fixed that build breakage too, and I like how you did it better.

I have this hideous construct...

ARCH=$(shell uname -m)
--with-libevent-dir=$(shell pwd)/../pkgs \
--with-openssl-dir=$(shell pwd)/../../rumprun/rumprun-extsrc/rumprun-$(ARCH) \ 
--with-zlib-dir=$(shell pwd)/../../rumprun/rumprun-extsrc/rumprun-$(ARCH) \

...whereas you have this thing of relative beauty...

--with-libevent-dir=$(RUMPRUN_PKGS_DIR) \
--with-openssl-dir=$(RUMPRUN_SYSROOT) \
--with-zlib-dir=$(RUMPRUN_SYSROOT) \

:)

**Comment by gandro** [comment]
Yeah, sorry for not coordinating with you first when fixing it (#103). But since I was the one who merged the code, I felt responsible.

**Comment by anttikantee** [comment]
You merge your changes by tarring up your repo (no joke!), running `git pull --rebase`, then editing the conflicts out, and then doing a web search for how merging works.  If you've already committed your changes, I think it's a bit different, but I can't quite remember how it goes.  The tarball is for when, if you're like me, screw the process up and end up with an unrecoverable local git repo.

Can't imagine non-advanced computers not having buildings.

You should read my Finnish writings, I think they're much better.

Yea it was @gandro who produced the elegant fix.  btw, I'm planning to add openssl to rumprun-packages, I'm absolutely tired of having to update src-netbsd all the time because of it.

**Comment by supradix** [comment]
@gandro No worries.  Thanks for fixing it, and more elegantly than I did too. :)  Much better than leaving it broken while waiting on a tortoise like me.  And besides, yeah, it was your fault, now that you mention it. ;)

@anttikantee Thanks.  Yeah, that's about what I thought, thus my fear and loathing (lol).  And, yeah, I committed them already.  No biggie though.  It's not like 30 large files all changed 30% or anything, after all.  And, yeah, I fear I'm probably a lot like you with the process.  Finally, I've adding learning Finnish to my queue; will advise when able to read. ;)

I passed out a while again.  Sorry, but I keep doing that in spite of all efforts.  Anyway, the 46 inode build seems to be running fine.  I'll tar and pull and merge and push and shake a bloody chicken leg at the gods now. :)

**Comment by supradix** [comment]
Oh, and nice on the openssl thing.  Good.  I was half planning to make openssl and zlib rumprun-packages on principle at some point myself.  Better you than me though. :)

**Comment by anttikantee** [comment]
I'm not sure I see the point of minimizing the inode count.  If you want read-only, use read-only.

**Comment by supradix** [comment]
Can't use read only for tor's data directory.  Tor needs to be able to write to _some_ files in it.

This, from the readme of my upcoming push, will hopefully explain the point...

"Note, however, that while the created filesystem image is indeed writable, the genext2fs command used limits its inodes to exactly those required by these tor configurations in order for tor to function.  The idea is to deny filesystem writability to potential h4x0rz while yet providing the required writability to tor.  We thereby not only get tor running in an extremely limited unikernel environment, but effectively running on a read only filesystem as well.  If the configuration is changed such that tor will need to write more files, the value of the -N option used by genext2fs will therefore need to be increased accordingly.  Yes, I've been called paranoid before, more than once even. ;)"

And when I get done fully groking the intricacies of git-rebase(1), as advised in the --rebase section of git-pull(1) as follows...

" Note
               This is a potentially dangerous mode of operation. It rewrites
               history, which does not bode well when you published that
               history already. Do not use this option unless you have read
               git-rebase(1) carefully."

...I will sync everything up. :)  I'm nearing satisfaction at this point though, so it shouldn't be too much longer now.

Also, the less paranoid can just eliminate use of genext2fs's -N option all together, if so desired, but I tend to think less is more, especially with security stuff. :)

**Comment by anttikantee** [comment]
How is it read-only if it's possible to change the contents of files?  Anyone can also rename existing files to new names!  It's just a bad idea to pretend that limiting the number of inodes gives you anything except degraded usability.  Also, please, don't use "h4x0rz" in documentation that someone is supposed to take seriously.

You can't push a history rewrite to rumprun-packages, so it's safe in that regard (at least not unless you "h4x0riz3" my account).

**Comment by anttikantee** [comment]
Oh, but please take extra care to make sure push only the commits you intended to instead of a ton of dirt.  If you open a pull request and merge it yourself (from the github ui), you get an extra chance to review your changes.

**Comment by supradix** [comment]
It's not read only, which is why I wrote, "effectively read only."  I wasn't really happy with that imprecise, confusing language though, especially granting my apprehension that it would lead to a deluge of discussion just like this, but there's no commonly used term for what it actually is, and I tried to take the easy way out.  I should say that it creates a "create no _new_ files after a specific daemon has been running for a little while" filesystem," but I trust you see the difficulty I was having with that.

While it is indeed of marginal utility (and I'm not in love with it or anything, so it can be eliminated from the package if you prefer), I do contend that it yet provides some efficacy, and security is all about layers.  It merely reduces the attack surface a little bit more.  In order to do as you suggest, an interloper, miscreant, attacker, or whatever more serious appellation is preferred, would indeed have to achieve as much, which is just a little bit more difficult, a little bit more likely to cause failure, and a good bit more likely to break tor's proper functioning, ultimately alerting its operator to the compromise, and in many cases, sooner than later, which is a lot better than the otherwise probably never scenario.  It merely occludes options a little bit more, and provides a little bit more probability of detection.  And as far as the "usability" issue goes, I think that's essentially a non-issue.  Tor is not really something than needs user interaction at the filesystem interface once it's running.  Pretty much all post startup interaction one might want is achieved via its ControlPort.  In fact, although I didn't add a ControlPort directive to these minimal configuration file examples, my "rumptor" instance does have that configured on its private, host facing only interface (e.g. 10.10.10.10) and I am using it, mostly via the nice 'arm' tor controller, as it so happens, and albeit with some dysfunctionality due to the fact that the tor relay it is controlling is actually running in a comparatively massively limited unikernel environment, which is something its creators don't seem to have anticipated.  Go figure.  Anyway, I am testing its limits in this environment, and they don't seem to be any further diminished by lack of a free inode.   Which brings me to the fact that I've been intending to add a ControlPort to these default configurations as well, but I seem to be getting behind a lot more than ahead, so I haven't gotten to that yet either.  And regarding the "h4x0rz" debacle, it was intended to be humorous, but I guess it fails.  No worries.  I'll endeavor to be less "amusing."  I did mention that I was apparently "weird," after all. Sorry. :)

Finally, yes, I've read that part of the commit documentation carefully at least three times, and will probably do so again before pulling a trigger.  I do certainly understand your concern there, and I was planning to go the safe route at first, in any case, which of course takes yet more time and effort, so, alas, and o woe is me, and all that rot.

**Comment by anttikantee** [comment]
It's called "security by obscurity".  Sure, more lawyers of security is better, but just coating any just any old layer with snake oil is not the way to go, at least if your perceived attackers know how to spell.  If it's not a usability issue, why are you documenting -N?

**Comment by supradix** [comment]
Upon further thought, I don't really want to configure ControlPort in the default config files, after all.  If I don't also configure CookieAuthentication, HashedControlPassword, or both, the control port will allow anyone on the host system to connect and control tor, and I don't really like the prospect of that, even granting listening on a non-routable address only.  And CookieAuthentication (the generally preferable approach, in most cases) can't be utilized in the unikernel scenario, at least not without first copying the generated control_auth_cookie file onto the host system, and anyone willing to do that can certainly take care of themselves.  Further, it doesn't pass sanity to configure a default password, of course, so HashedControlPassword (which is what I'm using at the moment, btw) is out too.

**Comment by supradix** [comment]
@anttikantee I've always heard it referred to as "security through obscurity," but it means the same thing either way.  I don't think it applies in this case, however, or snake oil either.  I do think the issues are subtle, the efficacy marginal, its use indeed somewhat onerous, and don't really want to bikeshed it to death toward no good end, in any case.  It's removed.  To answer your question, though, because I thought anyone setting out to run a tor relay like this in the first place could handle a little extra inconvenience. ;)

**Comment by supradix** [comment]
And, by the way, Simpson Garfinkel asked me to write the third edition of Practical Unix and Internet Security back in 1999, so I'm not totally unfamiliar with the concepts.  I started, got annoyed by O'Reilly soon enough and quit.  I'm like that.  The guy that finished it wanted it more than I did anyway, I'm sure.  Good for him.

**Pull request closed without merging**
