### PR TITLE
zeromq with two tests and benchmark

### PR DESCRIPTION
**Pull request by kvart2006**

### CODE REVIEW

**Comment by anttikantee** [comment]
Thanks, looks interesting, and I'm especially happy that you are publishing your benchmarks.

A few notes:
* "compile by typing _Makefile_" is probably a typo.
* what does "rumprun qemu is irrelevant in this context" mean? no overhead? too slow? what about kvm? (sorry I looked just at the text, as viewing the diff does not show images)

Also, there is no need to close and reopen pull requests. Just edit your own branch, squash the commits as necessary (with `git rebase`), and force push to your own branch. The result will be seen in the PR.

I'll send you a push access invitation once you address the above points.

**Comment by anttikantee** [comment]
Oh, and you should add this package to `.travis.yml` if possible.

**Comment by kvart2006** [comment]
Hi,
- Yes I wanted to say use Makefile.
- qemu seems really slow. Irrelevant is too strong, I agree to, even
thought, the comparison is, in general, made against docker. (At least this
is the productivity goal in my company).

You are right, I did not want to force push. I noted your remark for the
future.
Thanks

**Comment by anttikantee** [comment]
You still need to squash your commits into one to clean up the public history before merge. Also, you need to resolve the conflict.

**Comment by kvart2006** [comment]
Done; I cannot see the conflict. Sorry.

**Comment by kvart2006** [comment]
Antti,
Please tell me if something is still missing for the zeromq package.
Thanks,
Bela

**Comment by anttikantee** [comment]
You have closed this pull request and the files are unavailable at least from the github interface. That's the most pressing issue.

**Pull request closed without merging**
