### PR TITLE
localhost might not be default available in the env, explicitly set ip

### PR DESCRIPTION
**Pull request by maniankara**
fix for: https://github.com/rumpkernel/rumprun-packages/issues/94

### CODE REVIEW

**Comment by reuben-sutton** [comment]
This is great. Thank you!

**Comment by anttikantee** [comment]
I added /etc/hosts to Rumprun to make sure "localhost" is always resolvable (which was a good thing to add in any case).  Does that fix the issue?

**Comment by maniankara** [comment]
Fixed atleast for me.

**Comment by anttikantee** [comment]
Does it make sense to revert the doc change?

**Comment by maniankara** [comment]
Thats fine to revert it, as it works now without the -o param.
However, I think, there should be more options than just defaults. @reuben-sutton what do you say?

One more question, not related to this patch itself:
Is it worth to try to get a working rails out of this? I spend some time last weekend trying to sort this out and reached a point when "nokogiri.so" which is shipped as nokogiri gem needs re-compiling with rumpkernel. Please suggest, I can spend some more time on this if its worth. Thoughts?

**Comment by anttikantee** [comment]
I can't say if it's desirable to get rails working, but if you think it is, I will do my all to support that goal.

**Pull request merged**
