### PR TITLE
PHP: Add running make to nginx+php demo README

### PR DESCRIPTION
**Pull request by JelteF**
This seems like quite an important step.

### CODE REVIEW

**Comment by anttikantee** [comment]
[php package maintainer is on vacation this week, so I'm handling this]

I guess the "examples" section assumes that "instructions" have already been followed.  The various package READMEs are in disarray because we haven't figured out good templates that each readme should follow...

Do things work with the suggested patch?  It omits the baking step from "instructions".  Also, not entirely related, but looking at the steps, shouldn't step 3 be done before step 1?

**Comment by JelteF** [comment]
It is indeed not enough to get it running all by itself. You also need to do steps at the top of the page. However, after changing the content of `images/data` the image needs to be created again, otherwise the nginx IP remains unchanged.

**Comment by anttikantee** [comment]
Can you update your branch to reflect the above?  Also, please test that following the steps from scratch works.  After that, I can merge your contribution.  Thanks.

**Comment by JelteF** [comment]
I changed it a bit to mention it just rebuilds the image. It seems quite fair to assume that people did the top part of the README.

**Comment by anttikantee** [comment]
Thanks!

**Pull request merged**
