### PR TITLE
Update versions of mysql and php

### PR DESCRIPTION
**Pull request by JelteF**
These versions compile fine as well.

### CODE REVIEW

**Comment by Incognito** [comment]
Just as a reminder, PHP5.6 EOLs in 10 months, we'll need to move to PHP7 eventually (they skipped 6).

I tried doing this some months ago when PHP7 was unreleased, I'll put some effort towards that again in the next few weeks, I'm not sure how well all the includes will work.

**Comment by anttikantee** [comment]
@Incognito, what do you mean by "includes"?

Are php5 and php7 compatible?  Should we rename php->php5 and add a php7 ASAP?

**Comment by Incognito** [comment]
@anttikantee Sorry, I'm in web-dev brain-mode. Includes == external libs ( things put into RUMPRUN_SYSROOT like libxml2 ).

PHP5 is partially compatible with PHP7, but I think your suggestion makes sense. PHP should become PHP5. I'll spend some effort towards a PHP7 package.

**Comment by anttikantee** [comment]
So what's the issue with the external libs and php7?

**Comment by Incognito** [comment]
I don't have any qualified information. It was when I was new to the project and had troubles getting PHP to compile, so it may have simply been me incorrectly building things.

**Comment by anttikantee** [comment]
Ok, so we'll do the usual and assume it will just work unless proven otherwise ;-)

**Comment by JelteF** [comment]
It seems the discussion is very much straying from my original pull request. Are my changes still being considered?

**Comment by anttikantee** [comment]
@JelteF Sure they are.  The maintainer will process them when he returns from vacation (next week?).  If you consider them urgent (e.g. they fix security vulnerabilities) I can merge them now, but otherwise I prefer to wait for the maintainer to handle it.

**Comment by JelteF** [comment]
All right, as far as I know they are not urgent.

**Comment by anttikantee** [comment]
Of course, if you contribute entirely new packages, you get to be the maintainer and make those decisions ;-)

**Comment by mato** [comment]
Thanks for these, I'll merge them in a day or two, right after I get some form of Travis builds for -packages sorted.

**Comment by mato** [comment]
Merged, thanks!

**Pull request merged**
