### PR TITLE
Add Tor package

### PR DESCRIPTION
**Pull request by supradix**
Due to my GitHub incompetence, I screwed up my original pull request for this.  @gandro kindly offered to create a surrogate pull request and than helped me to straighten out and re-submit mine properly.  As a result, the discussion thread was begun here...

Add Tor support https://github.com/rumpkernel/rumprun-packages/pull/101

Please see this first for historical reference.

### CODE REVIEW

**Comment by gandro** [comment]
Great, thanks!

**Comment by anttikantee** [comment]
Thanks to both of you.

The travis build seems broken, see:
https://travis-ci.org/rumpkernel/rumprun-packages/builds/128760303
and more specifically:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/128760326/log.txt
Seems like it's complaining about an option which is given.  Weird, but someone needs to fix it.

@supradix I forgot yesterday that normally package maintainers are given push access to the repo so that they can fix problems with packages they maintain (as documented in http://repo.rumpkernel.org/rumprun-packages#contributing-new-packages).  I'll send you an invite.

Oh, and the paper which mentions Tor is "Environmental Independence: BSD Networking in Userspace", linked from the wiki (General Info -> Publications).  That said, don't hold everything the paper says as the final truth, that paper was written almost 8 years ago ...

**Comment by supradix** [comment]
Yes, that option is indeed given, and it consequently built fine for me, so weird indeed.
I'll try to track down the culprit.

@anttikantee I'm all hooked up now.  Thanks for the invite. :)
And thanks for the paper citation too.  I'll read it and watch the associated video.
I'm obviously interested in such things, and, hey, you're even pretty quotable. ;)

**Comment by anttikantee** [comment]
I think @gandro fixed travis already.

Bah, I should've opened a separate issue for the travis problem.

I would've waste too much time on the prehistoric papers.  Just open the pdf, search for Tor, look at it for 10s, chuckle, and move on.

**Pull request merged**
