### PR TITLE
add "Known Issues" for redis.

### PR DESCRIPTION
**Pull request by kaveman-**

### CODE REVIEW

**Comment by anttikantee** [comment]
Can you just put that in the overview?  Not sure everyone will scroll to below examples looking for "known issues".

**Comment by kaveman-** [comment]
moved under overview.

**Comment by kaveman-** [comment]
and removed the empty line at the end.

**Comment by anttikantee** [comment]
awesome.  thanks!

**Comment by kaveman-** [comment]
No, thank you for the git lesson!

**Pull request merged**
