### PR TITLE
Add Node.js as a package

### PR DESCRIPTION
**Pull request by davedoesdev**
Node 4.1.1

### CODE REVIEW

**Comment by anttikantee** [comment]
Not sure why you had to open a new PR, you should be able to just push to your old branch with git push -f.

Anyway, one mandatory nit: can you put the pkgsrc patches e.g. into patches/pkgsrc?  "rm -rf dl" is sort of an idiom when you want to nuke the files the package downloads, so it's suboptimal if part of the package goes with it.

Non-mandatory nit: the commit message could be simpler, just "add node.js as a package".  I don't think people reading the history a year from now will be interested in the squashing that they can't see.

Almost there ;-)

**Comment by anttikantee** [comment]
ready to merge?

**Comment by davedoesdev** [comment]
Yes. I just did a build from scratch to check.

It'll have to live without an app bundler until I get round to it. I've had good experience with Webpack before so might use that.

**Comment by anttikantee** [comment]
Thanks!

Could I ask you to send a small announcement of your work to the rumpkernel-users mailing list?

**Comment by anttikantee** [comment]
tested it too, seems to work
(guess my host is a bit slow .... ;-)

**Comment by Incognito** [comment]
:+1: Excited to play with this. Thanks :)

**Pull request merged**
